### ISSUE TITLE
I want to add the uwe5621ds driver to the kernel in S905X-P212.dtb, how should I compile it.

### ISSUE THREAD

**Issue by Windrunner20** [unifreq/linux-5.10.y#2]
include network &bluetooth driver 
I'm a rookie XD
thanks
https://github.com/Stane1983/uwe5621-aml

**Comment by unifreq** [comment]
I don't have this hardware, this driver is only provided to some netizens who need it for testing, and I am not testing it myself.

**Comment by maskedeken** [comment]
> include network &bluetooth driver I'm a rookie XD thanks https://github.com/Stane1983/uwe5621-aml

It is not compatible with the 5.x kernel, only works for 4.x
